#!/usr/bin/env bash
# Standalone C0.5 2xH100 launcher. Does not source or exec any launcher.
#SBATCH --job-name=bace_c05
#SBATCH --partition=c23g
#SBATCH --account=rwth2089
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=244G
#SBATCH --gres=gpu:2
#SBATCH --time=15:00:00
#SBATCH --chdir=.
#SBATCH --output=slurm/%x-%j.out
#SBATCH --error=slurm/%x-%j.err
set -euo pipefail
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd); REPO=$(cd "${SCRIPT_DIR}/../../.." && pwd); WORK_BACE=$(cd "${REPO}/.." && pwd); ROOT=$(cd "${WORK_BACE}/.." && pwd); EXP=${WORK_BACE}/experiments/alfworld-qwen2.5-1.5b-exact
MODEL=${ROOT}/model_down/model/Qwen2.5-1.5B-Instruct; TRAIN=${ROOT}/data/text/train.parquet; VAL=${ROOT}/data/text/test.parquet
SEED=${BACE_SEED:-0}; TARGET=${TARGET_STEP:-150}; RUN=${BACE_RUN_NAME:-bace_c05_opt_seed${SEED}_20260908}; SAVE=${SAVE_FREQ:-5}; KEEP=${MAX_CHECKPOINTS:-2}
[[ "${SEED}" =~ ^[0-9]+$ && "${TARGET}" =~ ^[0-9]+$ && "${RUN}" =~ ^[A-Za-z0-9_.-]+$ && "${KEEP}" =~ ^(1|2)$ ]]
ART=${EXP}/bace_artifacts/${RUN}; CKPT=${EXP}/checkpoints/${RUN}; ROLL=${EXP}/rollout_trajectories/${RUN}; TB=${EXP}/tensorboard/${RUN}; META=${EXP}/run_metadata/${RUN}/${SLURM_JOB_ID:-local}; REPORT=${EXP}/trace_validation/${RUN}; LOG=${EXP}/logs/${RUN}/${SLURM_JOB_ID:-local}.log
CONDA_BASE=${CONDA_BASE:-${HOME}/miniforge3}; VERL_AGENT_ENV=${VERL_AGENT_ENV:-${ROOT}/verl-agent}
module purge; module load GCCcore/13.3.0; module load CUDA/12.8.0; source "${CONDA_BASE}/etc/profile.d/conda.sh"; conda activate "${VERL_AGENT_ENV}"
unset VLLM_ATTENTION_BACKEND; export ALFWORLD_DATA=${ALFWORLD_DATA:-${HOME}/.cache/alfworld} HF_DATASETS_OFFLINE=1 HF_HUB_OFFLINE=1 PYTHONNOUSERSITE=1 TOKENIZERS_PARALLELISM=false
export OMP_NUM_THREADS=1 OMP_THREAD_LIMIT=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 NUMEXPR_MAX_THREADS=1 VECLIB_MAXIMUM_THREADS=1 RAYON_NUM_THREADS=1 MALLOC_ARENA_MAX=2
unset ROCR_VISIBLE_DEVICES HIP_VISIBLE_DEVICES LOCAL_RANK LOCAL_WORLD_SIZE RANK WORLD_SIZE MASTER_ADDR MASTER_PORT
for p in "${MODEL}" "${TRAIN}" "${VAL}" "${ALFWORLD_DATA}"; do [[ -e "${p}" ]] || { echo "Missing ${p}" >&2; exit 2; }; done
mkdir -p "${ART}" "${CKPT}" "${ROLL}" "${TB}" "${META}" "${REPORT}" "$(dirname "${LOG}")"
RTMP=/tmp/bace_ray_${USER}_${SLURM_JOB_ID:-local_c05}; mkdir -p "${RTMP}/ray" "${RTMP}/hf"; export TMPDIR=${RTMP} RAY_TMPDIR=${RTMP} HF_DATASETS_CACHE=${RTMP}/hf
[[ "${DRY_RUN:-0}" != 1 && -f "${CKPT}/latest_checkpointed_iteration.txt" ]] && python3 ${REPO}/examples/bace_gigpo/prune_checkpoints.py "${CKPT}" --keep "${KEEP}" --output "${META}/prune_before.json"
CMD=(python3 -m verl.trainer.main_ppo
algorithm.adv_estimator=bace_gigpo algorithm.bace.enabled=true algorithm.bace.variant=batch_erv_exact algorithm.bace.acquisition=batch_erv_exact algorithm.bace.topology=dynamic algorithm.bace.dynamic_root_generation=staged algorithm.bace.staged_root_batching=packed algorithm.bace.branch_execution_mode=selected_worker algorithm.bace.branch_pool_mode=main_reuse algorithm.bace.root_active_executor=true algorithm.bace.total_leaf_budget=8 algorithm.bace.min_natural_roots=2 algorithm.bace.capacity_correction_batch_size=4 algorithm.bace.max_branches_per_anchor=2 algorithm.bace.competence_threshold=0.5 algorithm.bace.history_initial_mean=0.10 algorithm.bace.history_initial_strength=2.0 algorithm.bace.history_forgetting=0.8 algorithm.bace.history_transfer_fraction=0.1 algorithm.bace.history_min_strength=2.0 algorithm.bace.history_max_strength=8.0 algorithm.bace.local_prior_strength=2.0 algorithm.bace.batch_erv_threshold=0.005 algorithm.bace.batch_erv_tie_abs_tolerance=1.0e-12 algorithm.bace.batch_erv_tie_rel_tolerance=1.0e-10 algorithm.bace.invalid_action_mode=strict_identity algorithm.bace.tie_break_identity_mode=stable_v1 algorithm.bace.local_credit_mode=occurrence algorithm.bace.credit_mode=c0_5_origin_family_local_mean algorithm.bace.tree_credit_mode=current algorithm.bace.macro_normalization_mode=stable_occurrence algorithm.bace.tree_ppo_padding_mode=copy_trainable algorithm.bace.artifacts.enabled=true algorithm.bace.artifacts.directory="${ART}" algorithm.bace.artifacts.include_token_arrays=true algorithm.bace.artifacts.fsync=false algorithm.bace.replay.compare_action_set=true algorithm.bace.replay.max_origin_retries=1
data.train_files="${TRAIN}" data.val_files="${VAL}" data.train_batch_size=16 data.val_batch_size=128 data.max_prompt_length=2048 data.max_response_length=512 data.filter_overlong_prompts=True data.truncation=error data.return_raw_chat=True actor_rollout_ref.model.path="${MODEL}" actor_rollout_ref.actor.optim.lr=1e-6 actor_rollout_ref.model.use_remove_padding=True actor_rollout_ref.actor.ppo_mini_batch_size=256 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=32 actor_rollout_ref.actor.use_kl_loss=True actor_rollout_ref.actor.kl_loss_coef=0.01 actor_rollout_ref.actor.kl_loss_type=low_var_kl actor_rollout_ref.actor.use_torch_compile=True actor_rollout_ref.model.enable_gradient_checkpointing=True actor_rollout_ref.actor.fsdp_config.param_offload=False actor_rollout_ref.actor.fsdp_config.optimizer_offload=False actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=32 actor_rollout_ref.rollout.tensor_model_parallel_size=2 actor_rollout_ref.rollout.name=vllm actor_rollout_ref.rollout.gpu_memory_utilization=0.6 actor_rollout_ref.rollout.max_num_batched_tokens=8192 actor_rollout_ref.rollout.max_num_seqs=1024 actor_rollout_ref.rollout.enable_chunked_prefill=False actor_rollout_ref.rollout.enforce_eager=False actor_rollout_ref.rollout.free_cache_engine=False actor_rollout_ref.rollout.val_kwargs.temperature=0.4 actor_rollout_ref.rollout.val_kwargs.do_sample=True actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=32 actor_rollout_ref.ref.fsdp_config.param_offload=True actor_rollout_ref.actor.use_invalid_action_penalty=True actor_rollout_ref.actor.invalid_action_penalty_coef=0.1 algorithm.use_kl_in_reward=False algorithm.gamma=0.95 algorithm.gigpo.step_advantage_w=1.0 algorithm.gigpo.mode=mean_std_norm env.env_name=alfworld/AlfredTWEnv env.seed="${SEED}" env.max_steps=50 env.rollout.n=8 env.resources_per_worker.num_cpus=0.1 trainer.critic_warmup=0 "trainer.logger=['console','wandb','tensorboard']" trainer.project_name=verl_agent_alfworld trainer.experiment_name="${RUN}" trainer.device=cuda trainer.n_gpus_per_node=2 trainer.nnodes=1 trainer.test_freq=5 trainer.total_epochs=150 trainer.val_before_train=True trainer.validate_on_last_step=True trainer.save_freq="${SAVE}" trainer.total_training_steps="${TARGET}" trainer.default_local_dir="${CKPT}" trainer.rollout_data_dir="${ROLL}" trainer.resume_mode=auto trainer.max_actor_ckpt_to_keep="${KEEP}" ray_init.num_cpus=32 +ray_init._temp_dir="${RTMP}/ray" +ray_init.include_dashboard=False)
printf '%q ' "${CMD[@]}" > "${META}/resolved_command.sh"; printf '\n' >> "${META}/resolved_command.sh"; printf 'method=C0.5\nseed=%s\ncredit_mode=c0_5_origin_family_local_mean\nscheduling_profile=optimized\n' "${SEED}" > "${META}/run_metadata.txt"
[[ "${DRY_RUN:-0}" == 1 ]] && { echo "DRY_RUN: ${META}/resolved_command.sh"; exit 0; }
python3 ${ROOT}/work-BACE/deploy/gpu/check_gpu_environment.py --expected-gpus 2 --model-path "${MODEL}" --alfworld-data "${ALFWORLD_DATA}" --output "${META}/preflight.json"
set +e; "${CMD[@]}" 2>&1 | tee -a "${LOG}"; STATUS=${PIPESTATUS[0]}; set -e; printf 'train_exit_code=%s\n' "${STATUS}" >> "${META}/run_metadata.txt"
if find "${ART}" -name summary.json -print -quit | grep -q .; then python3 -m recipe.bace_gigpo.validate_trace "${ART}" --output "${REPORT}/${SLURM_JOB_ID:-local}_final.json"; fi
[[ -f "${CKPT}/latest_checkpointed_iteration.txt" ]] && python3 ${REPO}/examples/bace_gigpo/prune_checkpoints.py "${CKPT}" --keep "${KEEP}" --output "${META}/prune_after.json"
exit "${STATUS}"
