#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
export GPU_COUNT=1
export BACE_RUN_NAME=${BACE_RUN_NAME:-bace_alfworld_qwen2_5_1_5b_1gpu_debug}
export TRAIN_DATA_SIZE=${TRAIN_DATA_SIZE:-2}
export VAL_DATA_SIZE=${VAL_DATA_SIZE:-2}
export ENV_MAX_STEPS=${ENV_MAX_STEPS:-4}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-128}
export PPO_MINI_BATCH=${PPO_MINI_BATCH:-16}
export ACTOR_MICRO_BATCH=${ACTOR_MICRO_BATCH:-1}
export LOGPROB_MICRO_BATCH=${LOGPROB_MICRO_BATCH:-1}
export GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.35}
export MAX_NUM_BATCHED_TOKENS=${MAX_NUM_BATCHED_TOKENS:-4096}
export MAX_NUM_SEQS=${MAX_NUM_SEQS:-16}
export SAVE_FREQ=${SAVE_FREQ:--1}
export TEST_FREQ=${TEST_FREQ:--1}
export LOGGER_BACKENDS=${LOGGER_BACKENDS:-"['console']"}
export BACE_RESUME_MODE=${BACE_RESUME_MODE:-disable}
export SEGMENT_END_STEP=${SEGMENT_END_STEP:-1}
exec bash "${SCRIPT_DIR}/run_alfworld_h100.sh" "$@"
